////////////////////////////////////////////////////////////////////////////////
// Filename:    resource.h
// Description: This file defines the reousrce IDs for the resource file.
//              Note that #defines must be used for constants in this file because
//              the windres compiler is a C variant, not a C++ variant.
//
// Created:     2012-08-05 13:53:11
// Author:      Jacob Buysse
//                                                              Modification Log
// When       Who               Description
// ---------- ----------------- ------------------------------------------------
////////////////////////////////////////////////////////////////////////////////
#pragma once

//Menus
#define IDM_MAINFRAME 101

//Commands
#define ID_FILE_EXIT 1001
#define ID_FILE_NEW_PROJECT 1002
#define ID_FILE_OPEN_PROJECT 1003
#define ID_FILE_SAVE_PROJECT 1004
#define ID_FILE_CLOSE_PROJECT 1005
#define ID_SELECT_NEXT_CHARACTER_VERTICAL 1006
#define ID_SELECT_NEXT_CHARACTER_VERTICAL_EXTEND 1007
#define ID_SELECT_PREVIOUS_CHARACTER_VERTICAL 1008
#define ID_SELECT_PREVIOUS_CHARACTER_VERTICAL_EXTEND 1009
#define ID_SELECT_NEXT_WORD_VERTICAL 1010
#define ID_SELECT_NEXT_WORD_VERTICAL_EXTEND 1011
#define ID_SELECT_PREVIOUS_WORD_VERTICAL 1012
#define ID_SELECT_PREVIOUS_WORD_VERTICAL_EXTEND 1013
#define ID_SELECT_NEXT_LINE_VERTICAL 1014
#define ID_SELECT_NEXT_LINE_VERTICAL_EXTEND 1015
#define ID_SELECT_PREVIOUS_LINE_VERTICAL 1016
#define ID_SELECT_PREVIOUS_LINE_VERTICAL_EXTEND 1017
#define ID_SELECT_PAGEUP_VERTICAL 1018
#define ID_SELECT_PAGEUP_VERTICAL_EXTEND 1019
#define ID_SELECT_PAGEDOWN_VERTICAL 1020
#define ID_SELECT_PAGEDOWN_VERTICAL_EXTEND 1021
#define ID_SELECT_END_OF_LINE_VERTICAL 1022
#define ID_SELECT_END_OF_LINE_VERTICAL_EXTEND 1023
#define ID_SELECT_BEGINNING_OF_LINE_VERTICAL 1024
#define ID_SELECT_BEGINNING_OF_LINE_VERTICAL_EXTEND 1025
#define ID_SELECT_END_OF_FILE_VERTICAL 1026
#define ID_SELECT_END_OF_FILE_VERTICAL_EXTEND 1027
#define ID_SELECT_BEGINNING_OF_FILE_VERTICAL 1028
#define ID_SELECT_BEGINNING_OF_FILE_VERTICAL_EXTEND 1029
#define ID_SELECT_ALL 1030
#define ID_EDIT_COPY 1031
#define ID_EDIT_CUT 1032
#define ID_EDIT_PASTE 1033
#define ID_EDIT_UNDO 1034
#define ID_EDIT_REDO 1035
#define ID_EDIT_TABIFY 1036
#define ID_EDIT_INSERT_FILE_HEADER 1037
#define ID_EDIT_INSERT_ONE_TIME_INCLUDE 1038
#define ID_SELECT_SET_FOCUS 1039
#define ID_EDIT_OPEN_FILE 1040
#define ID_EDIT_DELETE 1041
#define ID_EDIT_TOGGLE_BOOKMARK 1042
#define ID_EDIT_NEXT_BOOKMARK 1043
#define ID_EDIT_PREVIOUS_BOOKMARK 1044

#define ID_FIRST_DOCUMENT_COMMAND ID_SELECT_NEXT_CHARACTER_VERTICAL
#define ID_LAST_DOCUMENT_COMMAND ID_EDIT_PREVIOUS_BOOKMARK

#define ID_FILE_CLOSE_DOCUMENT 2000
#define ID_FILE_OPEN_CONTAINING_FOLDER 2001
#define ID_FILE_CLOSE_ALL_DOCUMENTS 2002
#define ID_FILE_CLOSE_ALL_BUT_THIS 2003
#define ID_FILE_RENAME 2004
#define ID_FILE_CREATE_FOLDER 2005
#define ID_FILE_CREATE_FILE 2006
#define ID_FILE_ADD_EXISTING_FILE 2007
#define ID_FILE_CREATE_CLASS 2008
#define ID_BUILD_COMPILE 2009
#define ID_BUILD_MESSAGE 2010
#define ID_BUILD_CANCEL 2011
#define ID_BUILD_BUILD 2012
#define ID_BUILD_EXECUTE 2013
#define ID_BUILD_CLEAN 2014
#define ID_BUILD_REBUILD 2015
#define ID_FILE_PROJECT_SETTINGS 2016
#define ID_BUILD_EXECUTE_UNIT_TEST 2017
#define ID_BUILD_GOTO_ERROR 2018
#define ID_EDIT_FIND 2019
#define ID_EDIT_GOTO_LINE 2020
#define ID_EDIT_FIND_IN_FILES 2021
#define ID_TOOLS_EDIT_OPTIONS 2022
#define ID_EDIT_SWITCH_DOCUMENTS 2023

//Icons
#define IDI_APPLICATION_LARGE 101
#define IDI_APPLICATION_SMALL 102
#define IDI_FOLDER_CLOSED 103
#define IDI_FOLDER_OPEN 104
#define IDI_FILE 105
#define IDI_TEST_PENDING 106
#define IDI_TEST_RUNNING 107
#define IDI_TEST_SUCCESS 108
#define IDI_TEST_FAILED 109

//Accelerator tables
#define IDA_MAINFRAME 201

//Dialogs
#define IDD_NEW_PROJECT 101
#define IDD_NEW_FOLDER 102
#define IDD_NEW_FILE 103
#define IDD_NEW_CLASS 104
#define IDD_PROJECT_SETTINGS 105
#define IDD_GOTO_LINE 106
#define IDD_FIND_IN_FILES 107
#define IDD_EDIT_OPTIONS 108

//Controls
#define IDC_EDIT_DIRECTORY 101
#define IDC_EDIT_NAME 102
#define IDC_EDIT_NAMESPACE 103
#define IDC_OPTION_BIG4_NORMAL 104
#define IDC_OPTION_BIG4_NOCOPY 105
#define IDC_CHECK_BIG4_DEFAULT 106
#define IDC_OPTION_FILES_SOURCE 107
#define IDC_OPTION_FILES_INLINE 108
#define IDC_OPTION_FILES_HEADER 109
#define IDC_EDIT_FILENAME 110
#define IDC_COMBO_STANDARD 111
#define IDC_COMBO_SUBSYSTEM 112
#define IDC_COMBO_WARNINGS 113
#define IDC_CHECK_WARNINGS_AS_ERRORS 114
#define IDC_COMBO_OPTIMIZATION 115
#define IDC_CHECK_DEBUG 116
#define IDC_CHECK_MULTITHREADED 117
#define IDC_EDIT_INCLUDE_DIRECTORIES 118
#define IDC_EDIT_LIBRARIES 119
#define IDC_CHECK_UNIT_TEST 120
#define IDC_EDIT_LINE 121
#define IDC_LABEL_LINE 122
#define IDC_EDIT_FIND_TEXT 123

//Version
#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_REVISION 0
#define VERSION_BUILD 20120919
#define MAKE_VERSION_NUMBER_STRING_EX(major,minor,revision,build) #major "." #minor "." #revision "." #build
#define MAKE_VERSION_NUMBER_STRING(major,minor,revision,build) MAKE_VERSION_NUMBER_STRING_EX(major,minor,revision,build)
#define VERSION_NUMBER VERSION_MAJOR,VERSION_MINOR,VERSION_REVISION,VERSION_BUILD
#define VERSION_NUMBER_STRING MAKE_VERSION_NUMBER_STRING(VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION, VERSION_BUILD)

